### ISSUE TITLE
Can someone go in my acc get me a bunch of money for me pls

### ISSUE THREAD

**Issue by gotoprodighy** [PrabhakarRai/Nitro-type-car-hack#10]
Pls

**Comment by deadInside580** [comment]
hi i can for you

**Comment by gotoprodighy** [comment]
Ok can I trust you

**Comment by gotoprodighy** [comment]
Hello I give my stuff if you give your email to me

**Comment by PrabhakarRai** [comment]
Wrong place for discussion such things. Join discord server instead.  https://discord.gg/jPNAJffjuP
