### ISSUE TITLE
How do you get rid of the hack?

### ISSUE THREAD

**Issue by yic242** [PrabhakarRai/Nitro-type-car-hack#4]
How do you get rid of the hack?

**Comment by MariaJackson1** [comment]
its not working i see no cars in my nitri type garage

**Comment by kelvinlokelvin** [comment]
somehooe

**Comment by kelvinlokelvin** [comment]
yayeet

**Comment by kelvinlokelvin** [comment]
how to gett the hack

**Comment by savageemote1** [comment]
try to reset the nitro type account if still no cars make a new account and send your money to that account.

**Comment by PrabhakarRai** [comment]
The hack is patched now. However, to remove it, you have to disable the tamper monkey extension.
