### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by loloisda** [PrabhakarRai/Nitro-type-car-hack#7]
mine is not working

**Comment by PrabhakarRai** [comment]
This hack has been patched for now.. It requires an update.. so, it will not work until then.

**Comment by PrabhakarRai** [comment]
It is updated and working now. Follow the tutorial given on my blog.
[Madcap Hacker](https://www.theprabhakar.in/)

**Comment by loloisda** [comment]
What is nitotyper 2.1

**Comment by loloisda** [comment]
give me a hack on nitro type man you ga best hacker
